include: package:flutter_lints/flutter.yaml

linter:
  rules:
    prefer_const_constructors: true
    prefer_const_declarations: true
    avoid_print: true
    prefer_single_quotes: true
    require_trailing_commas: true
    prefer_final_locals: true
    avoid_final_parameters: true
    prefer_typing_uninitialized_variables: true
    no_leading_underscores_for_local_identifiers: true
    lines_longer_than_80_chars: false
    always_declare_return_types: true
    annotate_overrides: true
    avoid_dynamic_calls: false
    prefer_is_empty: true
    prefer_is_not_empty: true
    sort_child_properties_last: true
    use_key_in_widget_constructors: true
    sized_box_for_whitespace: true
    unnecessary_const: true
    unnecessary_new: true
    unnecessary_this: true
